import Button from "primevue/button";
import IconField from 'primevue/iconfield';
import InputIcon from 'primevue/inputicon';
import InputText from "primevue/inputtext";
import Password from "primevue/password";
import Skeleton from "primevue/skeleton";
import ProgressSpinner from "primevue/progressspinner";
import Breadcrumb from "primevue/breadcrumb";
import Calendar from "primevue/calendar";
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import Dropdown from 'primevue/dropdown';
import Checkbox from 'primevue/checkbox';
import RadioButton from 'primevue/radiobutton';
import Dialog from 'primevue/dialog';
import Textarea from 'primevue/textarea';
import Stepper from 'primevue/stepper';
import StepperPanel from 'primevue/stepperpanel';
import Toast from 'primevue/toast';
import InputNumber from 'primevue/inputnumber';
import FileUpload from 'primevue/fileupload';
import MultiSelect from 'primevue/multiselect';
import Paginator from 'primevue/paginator';

export function importComponents(app) {
  app.component("Button", Button);
  app.component("InputText", InputText);
  app.component("Password", Password);
  app.component("Skeleton", Skeleton);
  app.component("ProgressSpinner", ProgressSpinner);
  app.component("Breadcrumb", Breadcrumb);
  app.component("Calendar", Calendar);
  app.component("TabView", TabView);
  app.component("TabPanel", TabPanel);
  app.component("IconField", IconField);
  app.component("InputIcon", InputIcon);
  app.component("Accordion", Accordion);
  app.component("AccordionTab", AccordionTab);
  app.component("Dropdown", Dropdown);
  app.component("Checkbox", Checkbox);
  app.component("RadioButton", RadioButton);
  app.component("Dialog", Dialog);
  app.component("Textarea", Textarea);
  app.component("Stepper", Stepper);
  app.component("StepperPanel", StepperPanel);
  app.component("Toast", Toast);
  app.component("InputNumber", InputNumber);
  app.component("FileUpload", FileUpload);
  app.component("MultiSelect", MultiSelect);
  app.component("Paginator", Paginator);
}